config/routes.rb
Rails.application.routes.draw do
  resources :mensajes

  resource :sesion, only: [:new, :create, :destroy], controller: 'sesion'

  resources :personas

  root 'sesion#new'

end

app/models/mensaje.rb
class Mensaje < ActiveRecord::Base
  validates :cuerpo, :persona, presence: true

  belongs_to :persona
end

app/models/persona.rb
class Persona < ActiveRecord::Base
  has_secure_password

  validates :nombre, :apellido, presence: true

  has_many :mensajes, dependent: :destroy

  def to_s
    [nombre, apellido].compact.join ' '
  end

  def self.buscar termino
    where 'nombre LIKE :t OR apellido LIKE :t', t: "#{termino}%"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def persona_actual
    @persona_actual ||= Persona.find(session[:persona_id]) if session[:persona_id]
  end
  helper_method :persona_actual

  def requerir_persona
    redirect_to root_url, notice: t('sesion.unauthenticated') unless persona_actual
  end
end

app/controllers/mensajes_controller.rb
class MensajesController < ApplicationController
  before_action :requerir_persona
  before_action :set_mensaje, only: [:show, :edit, :update, :destroy]

  # GET /mensajes
  # GET /mensajes.json
  def index
    @mensajes = Mensaje.all
  end

  # GET /mensajes/1
  # GET /mensajes/1.json
  def show
  end

  # GET /mensajes/new
  def new
    @mensaje = Mensaje.new
  end

  # GET /mensajes/1/edit
  def edit
  end

  # POST /mensajes
  # POST /mensajes.json
  def create
    @mensaje = Mensaje.new(mensaje_params)

    respond_to do |format|
      if @mensaje.save
        format.html { redirect_to @mensaje, notice: t('.notice') }
        format.json { render :show, status: :created, location: @mensaje }
      else
        format.html { render :new }
        format.json { render json: @mensaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mensajes/1
  # PATCH/PUT /mensajes/1.json
  def update
    respond_to do |format|
      if @mensaje.update(mensaje_params)
        format.html { redirect_to @mensaje, notice: t('.notice') }
        format.json { render :show, status: :ok, location: @mensaje }
      else
        format.html { render :edit }
        format.json { render json: @mensaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mensajes/1
  # DELETE /mensajes/1.json
  def destroy
    @mensaje.destroy
    respond_to do |format|
      format.html { redirect_to mensajes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mensaje
      @mensaje = Mensaje.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mensaje_params
      params.require(:mensaje).permit(:cuerpo, :persona_id)
    end
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :requerir_persona
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.buscar(params[:q]).order 'apellido'
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: t('.notice') }
        format.json { render action: 'show', status: :created, location: @persona }
      else
        format.html { render action: 'new' }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: t('.notice') }
        format.json { render action: 'show', status: :ok, location: @persona }
      else
        format.html { render action: 'edit' }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:nombre, :apellido, :correo, :password, :password_confirmation)
    end
end

app/controllers/sesion_controller.rb
class SesionController < ApplicationController
  def new
  end

  def create
    persona = Persona.find_by(correo: sesion_params[:correo])

    if persona && persona.authenticate(sesion_params[:password])
      session[:persona_id] = persona.id
      redirect_to personas_url, notice: t('.notice')
    else
      flash.now.alert = t('.alert')
      render 'new'
    end
  end

  def destroy
    session[:persona_id] = nil

    redirect_to root_url, notice: t('.notice')
  end

  private

    def sesion_params
      params.require(:sesion).permit(:correo, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mensajes_helper.rb
module MensajesHelper
  def mensaje
    flash[:alert] || flash[:notice]
  end

  def clase_mensaje
    flash[:alert] ? 'alert-danger' : 'alert-info'
  end
end

app/helpers/personas_helper.rb
module PersonasHelper
  def ver_todos
    link_to t('.all'), personas_path if params[:q].present?
  end
end

app/views/comun/_mensajes.html.erb
<div class="alert <%= clase_mensaje %> alert-dismissable fade in">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong><%= mensaje %></strong>
</div>

app/views/comun/_menu.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Foro</a>
    </div>

    <div class="collapse navbar-collapse" id="menu">
      <ul class="nav navbar-nav">
        <li><%= link_to Persona.model_name.human(count: 0), personas_path %></li>
        <li><%= link_to Mensaje.model_name.human(count: 0), mensajes_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t('navigation.exit'), sesion_path, method: :delete %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Foro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'comun/mensajes' if mensaje %>
    <%= render 'comun/menu' if persona_actual %>
    <%= yield %>
  </div>
</body>
</html>

app/views/mensajes/_form.html.erb
<%= form_for(@mensaje) do |f| %>
  <% if @mensaje.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= t 'errors.template.header', model: Mensaje.model_name.human, count: @mensaje.errors.size %></h4>

      <ul>
        <% @mensaje.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :cuerpo %>
    <%= f.text_area :cuerpo, autofocus: true, class: 'form-control', rows: '5' %>
  </div>
  <div class="form-group">
    <%= f.label :persona_id %>
    <%= f.text_field(
      :persona,
      class: 'form-control',
      data: {
        autocomplete_for: '#mensaje_persona_id',
        autocomplete_url: personas_path
      }
    ) %>
    <%= f.hidden_field :persona_id %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/mensajes/edit.html.erb
<h2 class="text-muted"><%= t 'mensajes.edit.title' %></h2>

<%= render 'form' %>

<div class="pull-right">
  <%= link_to t('navigation.show'), @mensaje %> |
  <%= link_to t('navigation.back'), mensajes_path %>
</div>

app/views/mensajes/index.html.erb
<h2 class="text-muted"><%= t '.title' %></h2>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th><%= Mensaje.human_attribute_name 'cuerpo' %></th>
      <th><%= Mensaje.human_attribute_name 'persona' %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mensajes.each do |mensaje| %>
      <tr>
        <td><%= truncate mensaje.cuerpo %></td>
        <td><%= link_to mensaje.persona, mensaje.persona %></td>
        <td>
          <%= link_to mensaje, title: t('navigation.show') do %>
            <span class="glyphicon glyphicon-search"></span>
          <% end %>
        </td>
        <td>
          <%= link_to edit_mensaje_path(mensaje), title: t('navigation.edit') do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
        </td>
        <td>
          <%= link_to mensaje, title: t('navigation.destroy'), method: :delete, data: { confirm: t('messages.confirm') } do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.new'), new_mensaje_path, class: 'btn btn-primary' %>

app/views/mensajes/new.html.erb
<h2 class="text-muted"><%= t 'mensajes.new.title' %></h2>

<%= render 'form' %>

<div class="pull-right">
  <%= link_to t('navigation.back'), mensajes_path %>
</div>

app/views/mensajes/show.html.erb
<p>
  <span class="glyphicon glyphicon-arrow-right"></span>
  <%= @mensaje.persona %>
</p>

<blockquote>
  <%= simple_format @mensaje.cuerpo %>
</blockquote>


<%= link_to t('navigation.edit'), edit_mensaje_path(@mensaje) %> |
<%= link_to t('navigation.back'), mensajes_path %>

app/views/personas/_form.html.erb
<%= form_for(@persona) do |f| %>
  <% if @persona.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= t 'errors.template.header', model: Persona.model_name.human, count: @persona.errors.size %></h4>

      <ul>
        <% @persona.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :nombre %>
        <%= f.text_field :nombre, autofocus: true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :apellido %>
        <%= f.text_field :apellido, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :correo %>
        <%= f.text_field :correo, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/personas/edit.html.erb
<h2 class="text-muted"><%= t 'personas.edit.title' %></h2>

<%= render 'form' %>

<div class="pull-right">
  <%= link_to t('navigation.show'), @persona %> |
  <%= link_to t('navigation.back'), personas_path %>
</div>

app/views/personas/index.html.erb
<h2 class="text-muted"><%= t '.title' %></h2>

<%= form_for :persona, url: personas_path, method: :get do |f| %>
  <div class="row">
    <div class="col-md-10">
      <div class="form-group">
        <%= text_field_tag :q, params[:q], autofocus: true, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-2">
      <%= f.submit t('.search'), class: 'btn btn-default btn-block' %> <%= ver_todos %>
    </div>
  </div>
<% end %>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th><%= Persona.model_name.human %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= link_to "#{persona.nombre} #{persona.apellido}", persona %></td>
        <td>
          <%= link_to edit_persona_path(persona), title: t('navigation.edit') do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
        </td>
        <td>
          <%= link_to persona, title: t('navigation.destroy'), method: :delete, data: { confirm: t('messages.confirm') } do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.new'), new_persona_path, class: 'btn btn-primary' %>

app/views/personas/new.html.erb
<h2 class="text-muted"><%= t 'personas.new.title' %></h2>

<%= render 'form' %>

<div class="pull-right">
  <%= link_to t('navigation.back'), personas_path %>
</div>

app/views/personas/show.html.erb
<h1>
  <span class="glyphicon glyphicon-user"></span>
  <%= @persona.nombre %> <%= @persona.apellido %>
</h1>

<p>
  <%= mail_to @persona.correo %>
</p>

<%= link_to t('navigation.edit'), edit_persona_path(@persona) %> |
<%= link_to t('navigation.back'), personas_path %>

app/views/sesion/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="page-header text-center">
      <h2><%= t '.title' %></h2>
    </div>

    <div class="well">
      <%= form_for :sesion, url: sesion_path do |f| %>
        <div class="form-group">
          <%= f.label :correo, Persona.human_attribute_name('correo') %>
          <%= f.text_field :correo, autofocus: true, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password, Persona.human_attribute_name('password') %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="actions">
          <%= f.submit t('.submit'), class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>